name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true           # ✅ for themes like PaperMod
          fetch-depth: 0             # ✅ required for Hugo git info

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true             # ✅ required for SCSS (used by PaperMod)

      - name: Build site
